apiVersion: v1
kind: ServiceAccount
metadata:
  name: soc-analyst-agent
  namespace: soc-analyst
  labels:
    app.kubernetes.io/name: soc-analyst-agent
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: soc-platform
  annotations:
    # IRSA annotation - populated by Terraform output: soc_analyst_irsa_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/soc-analyst-staging-app-HASH"
    eks.amazonaws.com/sts-regional-endpoints: "true"
automountServiceAccountToken: true
